apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cluster-role-binding
  namespace: {{ .Values.namespace | default (include "schednex.namespace" . ) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: kube-system
